# permissions for end users to edit googlesheetsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: googlesheetsync-editor-role
rules:
- apiGroups:
  - sheetops.hairizuan.com
  resources:
  - googlesheetsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sheetops.hairizuan.com
  resources:
  - googlesheetsyncs/status
  verbs:
  - get