# permissions for end users to view googlesheetsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: googlesheetsync-viewer-role
rules:
- apiGroups:
  - sheetops.hairizuan.com
  resources:
  - googlesheetsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sheetops.hairizuan.com
  resources:
  - googlesheetsyncs/status
  verbs:
  - get
