
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployment
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - sheetops.hairizuan.com
  resources:
  - googlesheetsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sheetops.hairizuan.com
  resources:
  - googlesheetsyncs/status
  verbs:
  - get
  - patch
  - update
